<a href="https://colab.research.google.com/github/guojianx/try/blob/main/PyTorchLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch
x = torch.arange(4.0)
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

* torch.dot(x, x) => x·x 点乘表示求矩阵x的内积
* 输出结果中有一个隐式的求梯度函数 grad_fn = ...

In [15]:
y = 2 * torch.dot(x, x)

通过反向传播函数来计算y关于x每个分量的梯度

In [16]:
y.backward()
x.grad

tensor([ 0., 20., 40., 60.])

In [12]:
x.grad == 4 * x

tensor([ True, False, False, False])